# Airflow and Standard Library Includes
from airflow.sdk import dag, task, task_group
from airflow.exceptions import AirflowFailException
import logging, time, os
# For every database you connect to using Airflow you must install the
# provider.
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
# Airflow Operator for executing SQL from a file
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
# Pull in our custom operators
from includes.operators.MsSqlCopyOperator import MsSqlCopyOperator


# Notice the template_searchpath directive, it is used by the SQLExecuteQueryOperator
# to find your SQL files.
# For our airflow Docker install os.getcwd() returns '/opt/airflow'
@dag(
    schedule=None,
    catchup=False,
    tags=["IST346", "testing"],
    template_searchpath=os.path.join(os.getcwd(), 'dags', 'includes', 'sql')
)

def fact_rental():
    """
    Create the fact table for film rentals.

    Note that in this case there is no extract job, everything is already in stage and
    the fact table cannot be created until all of the dimensions are created with their
    final surrogate keys. In this case the surrogate keys are generated by an IDENTITY column
    in the [sakila_dwh] dimension tables, so we will need to look it up from there.
    """


    @task_group(group_id="load")
    def load():
        @task
        def truncate_dest():
            logger = logging.getLogger(__name__)
            # Get the connection to the database that we configured in Airflow
            hook_db = MsSqlHook(mssql_conn_id="cisat_sql")
            conn = hook_db.get_conn()
            # Get the cursor
            cursor = conn.cursor()
            # First truncate the table
            cursor.execute("truncate table [sakila_dwh].[fact_rental]")
            conn.commit()
            logger.info("finished truncating destination.")

        # In sakila_dwh dim_film has an identity column film_key, since it auto populates MS SQL seems to know
        # not to try to insert a values, and so the insert statement with no column names still works. However,
        # it would probably be best to rewrite the operator to specify column names, at least optionally.
        load_data = MsSqlCopyOperator(task_id = "load_fact_rental",
                                      src_conn_id = "cisat_sql", src_schema = "stage", src_table = "fact_rental",
                                      dest_conn_id = "cisat_sql", dest_schema = "sakila_dwh", dest_table = "fact_rental",
                                      batch_size = 500, bulk_copy=False)

        truncate_dest() >> load_data
        
    
    @task_group(group_id='transform')
    def transform():
        
        transform = SQLExecuteQueryOperator(
                        task_id='transform_data',
                        conn_id='cisat_sql',
                        sql='create_fact_rental.sql',
                    )

        @task
        def truncate():
            logger = logging.getLogger(__name__)
            # Get the connection to the database that we configured in Airflow
            hook_db = MsSqlHook(mssql_conn_id="cisat_sql")
            conn = hook_db.get_conn()
            # Get the cursor
            cursor = conn.cursor()
            # First truncate the [dim_date] table
            cursor.execute("truncate table [stage].[fact_rental]")
            conn.commit()
            logger.info("finished truncating [stage].[fact_rental]")

        @task
        def verify():
            logger = logging.getLogger(__name__)
            # Get the connection to the database that we configured in Airflow
            hook_db = MsSqlHook(mssql_conn_id="cisat_sql")
            conn = hook_db.get_conn()
            # Get the cursor
            cursor = conn.cursor()
            # In this case the transform is not adding any rows to the table
            # so a very simple (and not really sufficient) verification is to just
            # count the number of rows and compare them.
            verification_src = "select count(*) from [stage].[rental]"
            verification_dest = "select count(*) from [stage].[fact_rental]"
            cursor.execute(verification_src)
            row = cursor.fetchone()
            src_rows = row[0]
            cursor.execute(verification_dest)
            row = cursor.fetchone()
            dest_rows = row[0]
            if src_rows != dest_rows:
                raise AirflowFailException("Transform failed, [stage].[fact_rental] does not have the correct number of rows.")
            logger.info("Transform Verified Successfully")
        
        # first we truncate our stage table, then do the transform that loads dim_fact, then verify the transform
        truncate() >> transform >> verify()
    
    # first extract, then transform
    transform() >> load()

fact_rental()